name: Deploy to GitHub Pages

on:
  push:
    branches:
      - frontend-deploy
  pull_request: 
    branches:
        - frontend
        - main


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        cd client
        npm install
        npm run build
      env:
        REACT_APP_MAP_API_KEY: ${{ secrets.REACT_APP_MAP_API_KEY }}

    - name: Deploy
      run: npm run deploy
      env:
        REACT_APP_MAP_API_KEY: ${{ secrets.REACT_APP_MAP_API_KEY }}