name: Deploy to GitHub Pages

on:
  push:
    branches:
      - frontend-deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        cd client
        npm install
        npm run build
      env:
        REACT_APP_MAP_API_KEY: ${{ secrets.REACT_APP_MAP_API_KEY }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_KEY }}
        BRANCH: gh-pages
        FOLDER: dist